### ISSUE TITLE
animations checklist

### ISSUE THREAD

**Issue by chase-moskal** [benevolent-games/toolbox#30]
## specials
- `tpose` — *full keyframes on every bone*
- `spine_bend` — *additive*
- `spine_lean` — *additive*
  - [ ] lock alignment of shoulders and eyeline
- `spine_lean_crouch` — *additive*
  - [ ] just like spine_lean except for crouching instead of standing
- `hips_swivel` — *additive*
- `head_scale` — *additive*
- `grip_left`
- `grip_right`

## lower-body (keyframes below hips)
- [ ] move all spine activity to upper-body anims
- `jump`
- `stand`
	- `stand_forward`
	- `stand_backward`
	- `stand_leftward`
	- `stand_rightward`
	- `stand_sprint`
	- `stand_legadjust_left`
	- `stand_legadjust_right`
- `crouch`
	- `crouch_forward`
	- `crouch_backward`
	- `crouch_leftward`
	- `crouch_rightward`
	- `crouch_legadjust_left`
	- `crouch_legadjust_right`

## upper-body (keyframes above hips)
- `unarmed`
	- `unarmed_forward`
	- `unarmed_backward`
	- `unarmed_leftward`
	- `unarmed_rightward`
	- `unarmed_sprint`
- `fists`
	- `fists_forward`
	- `fists_backward`
	- `fists_leftward`
	- `fists_rightward`
	- `fists_sprint`
	- `fists_attack_1`
	- `fists_attack_2`
	- `fists_attack_3`
	- `fists_attack_4`
	- `fists_attack_5`
	- `fists_attack_6`
	- `fists_attack_7`
	- `fists_attack_8`
- `twohander`
	- `twohander_forward`
	- `twohander_backward`
	- `twohander_leftward`
	- `twohander_rightward`
	- `twohander_sprint`
	- `twohander_attack_1`
	- `twohander_attack_2`
	- `twohander_attack_3`
	- `twohander_attack_4`
	- `twohander_attack_5`
	- `twohander_attack_6`
	- `twohander_attack_7`
	- `twohander_attack_8`

**diagram of attack numbers**
```
  1       2
   \     /
6 — (7-8) — 3
   /     \
  5       4
```
- (1) left overhead
- (2) right overhead
- (3) right swing
- (4) right underhand
- (5) left underhand
- (6) left swing
- (7) left stab
- (8) right stab
